name: CI/CD Build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - 'feature/snehak'

jobs:
  create-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          path: ./go-src/
          format: spdx-json
          output-file: sbom.spdx.json
      - name: Report SPDX SBOM to Ketryx
        uses: Ketryx/ketryx-github-action@v1
        if: success() || failure()
        with:
          ketryx-url: ${{ vars.KETRYX_URL }}
          project: ${{ vars.KETRYX_PROJECT_SNEHA }}
          api-key: ${{ secrets.KETRYX_API_KEY_SNEHA }}
          commit-sha: ${{ github.event.pull_request.head.sha || github.sha }}
          build-name: ci-sbom
          spdx-json-path: |
                sbom.spdx.json
